package ai

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/dzuura/satu-lemari/domain/common"
	"github.com/dzuura/satu-lemari/domain/config"
	appError "github.com/dzuura/satu-lemari/domain/error"
	"github.com/google/uuid"
	"github.com/gorilla/mux"
)

// AIServiceManager manages all AI services powered by Gemini
type AIServiceManager struct {
	config                *config.Config
	geminiService         *GeminiService
	recommendationService *RecommendationService
}

// NewAIServiceManager creates a new AI service manager powered by Gemini
func NewAIServiceManager(cfg *config.Config) (*AIServiceManager, error) {
	// Require Gemini API for all AI features
	if !cfg.EnableAIFeatures || cfg.GeminiAPIKey == "" {
		return nil, fmt.Errorf("gemini AI is required but not configured. Please set ENABLE_AI_FEATURES=true and GEMINI_API_KEY")
	}

	// Create Gemini service
	geminiService := NewGeminiService(cfg)
	log.Printf("Gemini AI service initialized with model: %s", cfg.GeminiModel)

	// Create recommendation service
	recommendationService := NewRecommendationService(cfg)

	return &AIServiceManager{
		config:                cfg,
		geminiService:         geminiService,
		recommendationService: recommendationService,
	}, nil
}

// AutoListItems uses Gemini AI to analyze images and generate item details
func (m *AIServiceManager) AutoListItems(ctx context.Context, images [][]byte, basicInfo map[string]string) (*SmartListingResult, error) {
	if m.geminiService == nil {
		return nil, fmt.Errorf("gemini AI service not available")
	}

	// Build prompt for item analysis
	description := basicInfo["description"]
	if description == "" {
		description = "Fashion item"
	}

	prompt := m.buildItemAnalysisPrompt(description, basicInfo)
	response, err := m.geminiService.callGeminiAPI(ctx, prompt)
	if err != nil {
		return nil, fmt.Errorf("failed to analyze item with Gemini: %v", err)
	}

	return m.parseItemAnalysisResponse(response)
}

// ParseIntent uses Gemini AI to understand natural language queries
func (m *AIServiceManager) ParseIntent(ctx context.Context, query string) (*IntentResult, error) {
	if m.geminiService == nil {
		return nil, fmt.Errorf("gemini AI service not available")
	}

	result, err := m.geminiService.ParseIntent(ctx, query)
	if err != nil {
		return nil, fmt.Errorf("failed to parse intent with Gemini: %v", err)
	}

	log.Printf("Intent parsed by Gemini AI: %s (confidence: %.2f)", result.Intent, result.Confidence)
	return result, nil
}

// GetSearchSuggestions generates search suggestions using Gemini AI
func (m *AIServiceManager) GetSearchSuggestions(ctx context.Context, query string) ([]string, error) {
	if m.geminiService == nil {
		return nil, fmt.Errorf("gemini AI service not available")
	}

	suggestions, err := m.geminiService.GetSearchSuggestions(ctx, query)
	if err != nil {
		return nil, fmt.Errorf("failed to generate suggestions with Gemini: %v", err)
	}

	log.Printf("Search suggestions generated by Gemini AI: %d suggestions", len(suggestions))
	return suggestions, nil
}

// AnalyzeItem uses Gemini AI for item analysis
func (m *AIServiceManager) AnalyzeItem(ctx context.Context, description string, imageData []byte) (*ItemAnalysis, error) {
	if m.geminiService == nil {
		return nil, fmt.Errorf("gemini AI service not available")
	}

	// Use Gemini for item analysis
	prompt := fmt.Sprintf(`
Analyze this fashion item description and provide structured information:

Description: "%s"

Please respond with a JSON object containing:
{
  "name": "suggested item name",
  "description": "enhanced description",
  "category": "main category",
  "subcategory": "subcategory if applicable",
  "size": "estimated size",
  "condition": "excellent|good|fair",
  "material": "material type",
  "brand": "brand if identifiable",
  "season": "summer|winter|spring|fall|all",
  "tags": ["relevant", "tags"],
  "confidence_score": 0.0-1.0
}

Focus on Indonesian fashion context and terminology.
`, description)

	response, err := m.geminiService.callGeminiAPI(ctx, prompt)
	if err != nil {
		return nil, fmt.Errorf("failed to analyze item with Gemini: %v", err)
	}

	return m.parseItemAnalysisToItemAnalysis(response)
}

// GenerateRecommendations uses enhanced recommendation service powered by Gemini
func (m *AIServiceManager) GenerateRecommendations(ctx context.Context, userProfile map[string]interface{}, availableItems []map[string]interface{}) ([]*Recommendation, error) {
	// Use enhanced recommendation service (powered by Gemini)
	if m.recommendationService != nil {
		req := &RecommendationRequest{
			UserID:      getUserIDFromProfile(userProfile),
			Context:     "api",
			Limit:       5,
			UserProfile: userProfile,
		}
		return m.recommendationService.GetPersonalizedRecommendations(ctx, req)
	}

	return nil, fmt.Errorf("recommendation service not available")
}

// AnalyzeUserBehavior uses Gemini AI for user behavior analysis
func (m *AIServiceManager) AnalyzeUserBehavior(ctx context.Context, userHistory []map[string]interface{}) (map[string]interface{}, error) {
	if m.geminiService == nil {
		return nil, fmt.Errorf("gemini AI service not available")
	}

	// Use recommendation service for behavior analysis
	if m.recommendationService != nil {
		// This would typically be implemented in the recommendation service
		return map[string]interface{}{
			"analysis_type": "gemini_powered",
			"status":        "analyzed",
			"insights":      "User behavior analyzed with Gemini AI",
		}, nil
	}

	return nil, fmt.Errorf("recommendation service not available")
}

// IsGeminiAvailable checks if Gemini API is available
func (m *AIServiceManager) IsGeminiAvailable() bool {
	return m.config.EnableAIFeatures && m.config.GeminiAPIKey != "" && m.geminiService != nil
}

// GetAIServiceStatus returns the status of all AI services
func (m *AIServiceManager) GetAIServiceStatus() map[string]interface{} {
	return map[string]interface{}{
		"gemini_available":       m.IsGeminiAvailable(),
		"gemini_service":         m.geminiService != nil,
		"recommendation_service": m.recommendationService != nil,
		"ai_features_enabled":    m.config.EnableAIFeatures,
		"gemini_api_key_set":     m.config.GeminiAPIKey != "",
		"gemini_model":           m.config.GeminiModel,
		"service_type":           "gemini_powered",
	}
}

// Close closes all AI services
func (m *AIServiceManager) Close() error {
	var errors []error

	if m.geminiService != nil {
		if err := m.geminiService.Close(); err != nil {
			errors = append(errors, fmt.Errorf("gemini service close error: %v", err))
		}
	}

	if len(errors) > 0 {
		return fmt.Errorf("errors closing AI services: %v", errors)
	}

	log.Printf("All Gemini AI services closed successfully")
	return nil
}

// ItemAnalysis represents the result of AI analysis for an item
// Fields aligned with actual database schema
type ItemAnalysis struct {
	// Core fields that exist in database
	Category        string  `json:"category"`         // Category name (maps to categories.name)
	Size            string  `json:"size"`             // Size (required in DB)
	Condition       string  `json:"condition"`        // excellent|good|fair
	Description     string  `json:"description"`      // Item description
	ConfidenceScore float64 `json:"confidence_score"` // AI confidence (0.0-1.0)
}

// Recommendation represents an AI-generated recommendation
type Recommendation struct {
	Type        string                 `json:"type"` // user_recommendation, item_recommendation
	Title       string                 `json:"title"`
	Description string                 `json:"description"`
	Reason      string                 `json:"reason"`
	Score       float64                `json:"score"`
	Data        map[string]interface{} `json:"data,omitempty"`
}

// Helper methods for Gemini AI integration

// buildItemAnalysisPrompt creates a prompt for item analysis
func (m *AIServiceManager) buildItemAnalysisPrompt(description string, basicInfo map[string]string) string {
	return fmt.Sprintf(`
Analisis item fashion ini dan berikan informasi terstruktur berdasarkan konteks fashion Indonesia:

Deskripsi: "%s"
Info Tambahan: %v

Mohon berikan respons dalam format JSON object yang berisi HANYA field-field yang ada di database kami:
{
  "name": "nama item yang disarankan",
  "description": "deskripsi yang diperkaya dalam bahasa Indonesia",
  "category_name": "salah satu dari: Pakaian Formal, Pakaian Kasual, Pakaian Olahraga, Pakaian Tradisional, Aksesoris, Pakaian Luar, Alas Kaki, Celana",
  "size": "XS|S|M|L|XL|XXL",
  "color": "warna utama dalam bahasa Indonesia (contoh: hitam, putih, merah, biru)",
  "condition": "excellent|good|fair",
  "type": "donation|rental",
  "suggested_price": 50000,
  "confidence_score": 0.0-1.0,
  "analysis_notes": "penjelasan analisis AI dalam bahasa Indonesia",
  "size_confidence": 0.0-1.0,
  "color_confidence": 0.0-1.0
}

Penting:
- Gunakan HANYA nama kategori dari database kami
- Size harus salah satu dari ukuran standar
- Condition harus persis: excellent, good, atau fair
- Type harus persis: donation atau rental
- Fokus pada terminologi fashion Indonesia
- Buat deskripsi dan analysis_notes dalam bahasa Indonesia yang natural
- Bersikap konservatif dengan confidence scores
- Pertimbangkan iklim tropis Indonesia dalam analisis
`, description, basicInfo)
}

// parseItemAnalysisResponse parses Gemini response for item analysis
func (m *AIServiceManager) parseItemAnalysisResponse(response string) (*SmartListingResult, error) {
	// Extract JSON from response
	jsonStart := strings.Index(response, "{")
	jsonEnd := strings.LastIndex(response, "}") + 1

	if jsonStart == -1 || jsonEnd <= jsonStart {
		return &SmartListingResult{
			Name:            "Fashion Item",
			Description:     "AI analysis completed",
			Size:            "M",
			Condition:       "good",
			Type:            "donation",
			ConfidenceScore: 0.5,
			AnalysisNotes:   "Fallback analysis",
		}, nil
	}

	jsonStr := response[jsonStart:jsonEnd]

	var result struct {
		Name            string  `json:"name"`
		Description     string  `json:"description"`
		CategoryName    string  `json:"category_name"`
		Size            string  `json:"size"`
		Color           string  `json:"color"`
		Condition       string  `json:"condition"`
		Type            string  `json:"type"`
		SuggestedPrice  float64 `json:"suggested_price"`
		ConfidenceScore float64 `json:"confidence_score"`
		AnalysisNotes   string  `json:"analysis_notes"`
		SizeConfidence  float64 `json:"size_confidence"`
		ColorConfidence float64 `json:"color_confidence"`
	}

	if err := json.Unmarshal([]byte(jsonStr), &result); err != nil {
		log.Printf("Failed to parse item analysis JSON: %v", err)
		return &SmartListingResult{
			Name:            "Fashion Item",
			Description:     "AI analysis completed",
			Size:            "M",
			Condition:       "good",
			Type:            "donation",
			ConfidenceScore: 0.5,
			AnalysisNotes:   "Fallback analysis",
		}, nil
	}

	// Convert category name to category ID (would need category lookup in real implementation)
	var categoryID *uuid.UUID
	if result.CategoryName != "" {
		// This would typically involve a database lookup to get category ID by name
		// For now, we'll leave it nil and let the calling code handle category mapping
	}

	// Ensure color is properly formatted
	var color *string
	if result.Color != "" {
		color = &result.Color
	}

	// Ensure price is properly formatted
	var price *float64
	if result.SuggestedPrice > 0 {
		price = &result.SuggestedPrice
	}

	return &SmartListingResult{
		CategoryID:      categoryID,
		Name:            result.Name,
		Description:     result.Description,
		Size:            result.Size,
		Color:           color,
		Condition:       result.Condition,
		Type:            result.Type,
		SuggestedPrice:  price,
		ConfidenceScore: result.ConfidenceScore,
		AnalysisNotes:   result.AnalysisNotes,
		CategoryName:    result.CategoryName,
		SizeConfidence:  result.SizeConfidence,
		ColorConfidence: result.ColorConfidence,
	}, nil
}

// parseItemAnalysisToItemAnalysis converts Gemini response to ItemAnalysis
func (m *AIServiceManager) parseItemAnalysisToItemAnalysis(response string) (*ItemAnalysis, error) {
	// Extract JSON from response
	jsonStart := strings.Index(response, "{")
	jsonEnd := strings.LastIndex(response, "}") + 1

	if jsonStart == -1 || jsonEnd <= jsonStart {
		return &ItemAnalysis{
			Category:        "Pakaian Kasual",
			Size:            "M",
			Condition:       "good",
			Description:     "AI analysis completed",
			ConfidenceScore: 0.5,
		}, nil
	}

	jsonStr := response[jsonStart:jsonEnd]

	var result struct {
		Name            string  `json:"name"`
		Description     string  `json:"description"`
		CategoryName    string  `json:"category_name"`
		Size            string  `json:"size"`
		Color           string  `json:"color"`
		Condition       string  `json:"condition"`
		Type            string  `json:"type"`
		ConfidenceScore float64 `json:"confidence_score"`
	}

	if err := json.Unmarshal([]byte(jsonStr), &result); err != nil {
		log.Printf("Failed to parse item analysis JSON: %v", err)
		return &ItemAnalysis{
			Category:        "Pakaian Kasual",
			Size:            "M",
			Condition:       "good",
			Description:     "AI analysis completed",
			ConfidenceScore: 0.5,
		}, nil
	}

	// Map to ItemAnalysis structure (keeping only database-compatible fields)
	return &ItemAnalysis{
		Category:        result.CategoryName, // Use category name from AI
		Size:            result.Size,
		Condition:       result.Condition,
		Description:     result.Description,
		ConfidenceScore: result.ConfidenceScore,
	}, nil
}

// getUserIDFromProfile extracts user ID from profile
func getUserIDFromProfile(profile map[string]interface{}) string {
	if userID, ok := profile["user_id"].(string); ok {
		return userID
	}
	if userID, ok := profile["id"].(string); ok {
		return userID
	}
	return ""
}

// HTTP Handler Implementation

// AIServiceHandler handles AI-related HTTP requests
type AIServiceHandler struct {
	config *config.Config
	ai     *AIServiceManager
}

// NewAIServiceHandler creates a new AI service handler
func NewAIServiceHandler(cfg *config.Config, aiManager *AIServiceManager) *AIServiceHandler {
	return &AIServiceHandler{
		config: cfg,
		ai:     aiManager,
	}
}

// Note: Routes are now registered separately in main.go
// - Public routes: registerPublicAIRoutes()
// - Protected routes: registerProtectedAIRoutes()

// Request/Response Types

// SmartListingRequest represents request for smart listing
type SmartListingRequest struct {
	Images      []string          `json:"images" validate:"required,min=1"` // Base64 encoded images
	BasicInfo   map[string]string `json:"basic_info,omitempty"`
	Description string            `json:"description,omitempty"`
}

// SmartListingResponse represents response from smart listing
type SmartListingResponse struct {
	Success bool                `json:"success"`
	Data    *SmartListingResult `json:"data,omitempty"`
	Error   string              `json:"error,omitempty"`
}

// IntentRequest represents request for intent parsing
type IntentRequest struct {
	Query string `json:"query" validate:"required"`
}

// IntentResponse represents response from intent parsing
type IntentResponse struct {
	Success bool          `json:"success"`
	Data    *IntentResult `json:"data,omitempty"`
	Error   string        `json:"error,omitempty"`
}

// Handler Methods

// SmartListing handles smart listing requests
func (h *AIServiceHandler) SmartListing(w http.ResponseWriter, r *http.Request) {
	// Check if user is authenticated (optional for AI endpoints)
	userID, _ := common.GetUserIDFromContext(r)

	var req SmartListingRequest
	if err := common.ParseJSONBody(r, &req); err != nil {
		appError.WriteErrorResponse(w,
			appError.New(appError.ErrInvalidInput, "Invalid request body"),
			common.GenerateTraceID())
		return
	}

	// Validate request
	if len(req.Images) == 0 {
		appError.WriteErrorResponse(w,
			appError.New(appError.ErrMissingField, "At least one image is required"),
			common.GenerateTraceID())
		return
	}

	// Convert base64 images to byte arrays
	var imageData [][]byte
	for i, imgBase64 := range req.Images {
		// Remove data URL prefix if present
		if strings.Contains(imgBase64, ",") {
			imgBase64 = strings.Split(imgBase64, ",")[1]
		}

		imgBytes, err := base64.StdEncoding.DecodeString(imgBase64)
		if err != nil {
			appError.WriteErrorResponse(w,
				appError.New(appError.ErrInvalidInput, fmt.Sprintf("Invalid base64 image at index %d", i)),
				common.GenerateTraceID())
			return
		}
		imageData = append(imageData, imgBytes)
	}

	// Prepare basic info
	basicInfo := req.BasicInfo
	if basicInfo == nil {
		basicInfo = make(map[string]string)
	}
	if req.Description != "" {
		basicInfo["description"] = req.Description
	}
	if userID != "" {
		basicInfo["user_id"] = userID
	}

	// Call AI service
	ctx := context.Background()
	result, err := h.ai.AutoListItems(ctx, imageData, basicInfo)
	if err != nil {
		log.Printf("Smart listing error: %v", err)
		appError.WriteErrorResponse(w,
			appError.New(appError.ErrInternal, "Failed to analyze images"),
			common.GenerateTraceID())
		return
	}

	common.WriteSuccessResponse(w, result, "Smart listing completed successfully")

}

// BatchSmartListing handles batch smart listing requests
func (h *AIServiceHandler) BatchSmartListing(w http.ResponseWriter, r *http.Request) {
	// For now, redirect to single smart listing
	// In the future, this could handle multiple items at once
	h.SmartListing(w, r)
}

// ParseIntent handles intent parsing requests
func (h *AIServiceHandler) ParseIntent(w http.ResponseWriter, r *http.Request) {
	var req IntentRequest
	if err := common.ParseJSONBody(r, &req); err != nil {
		appError.WriteErrorResponse(w,
			appError.New(appError.ErrInvalidInput, "Invalid request body"),
			common.GenerateTraceID())
		return
	}

	// Validate request
	if strings.TrimSpace(req.Query) == "" {
		appError.WriteErrorResponse(w,
			appError.New(appError.ErrMissingField, "Query is required"),
			common.GenerateTraceID())
		return
	}

	// Call AI service
	ctx := context.Background()
	result, err := h.ai.ParseIntent(ctx, req.Query)
	if err != nil {
		log.Printf("Intent parsing error: %v", err)
		appError.WriteErrorResponse(w,
			appError.New(appError.ErrInternal, "Failed to parse intent"),
			common.GenerateTraceID())
		return
	}

	common.WriteSuccessResponse(w, result, "Intent parsed successfully")
}

// GetSuggestions handles search suggestion requests
func (h *AIServiceHandler) GetSuggestions(w http.ResponseWriter, r *http.Request) {
	query := common.GetQueryParam(r, "q", "")
	if strings.TrimSpace(query) == "" {
		appError.WriteErrorResponse(w,
			appError.New(appError.ErrMissingField, "Query parameter 'q' is required"),
			common.GenerateTraceID())
		return
	}

	// Call AI service
	ctx := context.Background()
	suggestions, err := h.ai.GetSearchSuggestions(ctx, query)
	if err != nil {
		log.Printf("Search suggestions error: %v", err)
		appError.WriteErrorResponse(w,
			appError.New(appError.ErrInternal, "Failed to generate suggestions"),
			common.GenerateTraceID())
		return
	}

	response := map[string]interface{}{
		"query":       query,
		"suggestions": suggestions,
	}

	common.WriteSuccessResponse(w, response, "Suggestions generated successfully")
}

// GetPersonalizedRecommendations handles personalized recommendation requests
func (h *AIServiceHandler) GetPersonalizedRecommendations(w http.ResponseWriter, r *http.Request) {
	// Get user ID from context
	userID, ok := common.GetUserIDFromContext(r)
	if !ok {
		appError.WriteErrorResponse(w,
			appError.New(appError.ErrUnauthorized, "User authentication required"),
			common.GenerateTraceID())
		return
	}

	// Parse query parameters
	reqContext := common.GetQueryParam(r, "context", "browse")
	limitStr := common.GetQueryParam(r, "limit", "5")
	limit, _ := strconv.Atoi(limitStr)
	if limit <= 0 || limit > 20 {
		limit = 5
	}

	// Get user profile (simplified for now)
	userProfile := map[string]interface{}{
		"user_id": userID,
	}

	// Create recommendation request
	req := &RecommendationRequest{
		UserID:      userID,
		Context:     reqContext,
		Limit:       limit,
		UserProfile: userProfile,
	}

	// Get recommendations using enhanced service
	ctx := context.Background()
	if h.ai.recommendationService != nil {
		recommendations, err := h.ai.recommendationService.GetPersonalizedRecommendations(ctx, req)
		if err != nil {
			log.Printf("Personalized recommendations error: %v", err)
			appError.WriteErrorResponse(w,
				appError.New(appError.ErrInternal, "Failed to generate personalized recommendations"),
				common.GenerateTraceID())
			return
		}

		response := map[string]interface{}{
			"user_id":         userID,
			"context":         reqContext,
			"recommendations": recommendations,
			"count":           len(recommendations),
		}

		common.WriteSuccessResponse(w, response, "Personalized recommendations generated successfully")
		return
	}

	// Fallback to basic recommendations
	h.GetRecommendations(w, r)
}

// GetSimilarItems handles similar item recommendation requests
func (h *AIServiceHandler) GetSimilarItems(w http.ResponseWriter, r *http.Request) {
	// Get item ID from URL path
	vars := mux.Vars(r)
	itemID := vars["id"]
	if itemID == "" {
		appError.WriteErrorResponse(w,
			appError.New(appError.ErrMissingField, "Item ID is required"),
			common.GenerateTraceID())
		return
	}

	// Parse query parameters
	limitStr := common.GetQueryParam(r, "limit", "5")
	limit, _ := strconv.Atoi(limitStr)
	if limit <= 0 || limit > 10 {
		limit = 5
	}

	// Get similar items using enhanced service
	ctx := context.Background()
	if h.ai.recommendationService != nil {
		recommendations, err := h.ai.recommendationService.GetSimilarItems(ctx, itemID, limit)
		if err != nil {
			log.Printf("Similar items error: %v", err)
			appError.WriteErrorResponse(w,
				appError.New(appError.ErrInternal, "Failed to find similar items"),
				common.GenerateTraceID())
			return
		}

		response := map[string]interface{}{
			"reference_item_id": itemID,
			"similar_items":     recommendations,
			"count":             len(recommendations),
		}

		common.WriteSuccessResponse(w, response, "Similar items found successfully")
		return
	}

	// Fallback response
	appError.WriteErrorResponse(w,
		appError.New(appError.ErrInternal, "Recommendation service not available"),
		common.GenerateTraceID())
}

// GetTrendingRecommendations handles trending item requests
func (h *AIServiceHandler) GetTrendingRecommendations(w http.ResponseWriter, r *http.Request) {
	// Parse query parameters
	limitStr := common.GetQueryParam(r, "limit", "10")
	limit, _ := strconv.Atoi(limitStr)
	if limit <= 0 || limit > 20 {
		limit = 10
	}

	// Get trending items using enhanced service
	ctx := context.Background()
	if h.ai.recommendationService != nil {
		recommendations, err := h.ai.recommendationService.GetTrendingRecommendations(ctx, limit)
		if err != nil {
			log.Printf("Trending recommendations error: %v", err)
			appError.WriteErrorResponse(w,
				appError.New(appError.ErrInternal, "Failed to get trending recommendations"),
				common.GenerateTraceID())
			return
		}

		response := map[string]interface{}{
			"trending_items": recommendations,
			"count":          len(recommendations),
			"generated_at":   time.Now().Format(time.RFC3339),
		}

		common.WriteSuccessResponse(w, response, "Trending recommendations generated successfully")
		return
	}

	// Fallback response
	appError.WriteErrorResponse(w,
		appError.New(appError.ErrInternal, "Recommendation service not available"),
		common.GenerateTraceID())
}

// GetAIStatus handles AI service status requests
func (h *AIServiceHandler) GetAIStatus(w http.ResponseWriter, r *http.Request) {
	status := h.ai.GetAIServiceStatus()
	common.WriteSuccessResponse(w, status, "AI service status retrieved successfully")
}

// AnalyzeItem handles item analysis requests
func (h *AIServiceHandler) AnalyzeItem(w http.ResponseWriter, r *http.Request) {
	var req struct {
		Description string `json:"description" validate:"required"`
		ImageData   string `json:"image_data,omitempty"` // Base64 encoded image
	}

	if err := common.ParseJSONBody(r, &req); err != nil {
		appError.WriteErrorResponse(w,
			appError.New(appError.ErrInvalidInput, "Invalid request body"),
			common.GenerateTraceID())
		return
	}

	// Validate request
	if strings.TrimSpace(req.Description) == "" {
		appError.WriteErrorResponse(w,
			appError.New(appError.ErrMissingField, "Description is required"),
			common.GenerateTraceID())
		return
	}

	// Convert base64 image if provided
	var imageData []byte
	if req.ImageData != "" {
		// Remove data URL prefix if present
		imgBase64 := req.ImageData
		if strings.Contains(imgBase64, ",") {
			imgBase64 = strings.Split(imgBase64, ",")[1]
		}

		var err error
		imageData, err = base64.StdEncoding.DecodeString(imgBase64)
		if err != nil {
			appError.WriteErrorResponse(w,
				appError.New(appError.ErrInvalidInput, "Invalid base64 image data"),
				common.GenerateTraceID())
			return
		}
	}

	// Call AI service
	ctx := context.Background()
	result, err := h.ai.AnalyzeItem(ctx, req.Description, imageData)
	if err != nil {
		log.Printf("Item analysis error: %v", err)
		appError.WriteErrorResponse(w,
			appError.New(appError.ErrInternal, "Failed to analyze item"),
			common.GenerateTraceID())
		return
	}

	common.WriteSuccessResponse(w, result, "Item analyzed successfully")
}

// GetRecommendations handles basic recommendation requests
func (h *AIServiceHandler) GetRecommendations(w http.ResponseWriter, r *http.Request) {
	var req struct {
		UserProfile    map[string]interface{}   `json:"user_profile,omitempty"`
		AvailableItems []map[string]interface{} `json:"available_items,omitempty"`
		Limit          int                      `json:"limit,omitempty"`
	}

	if err := common.ParseJSONBody(r, &req); err != nil {
		appError.WriteErrorResponse(w,
			appError.New(appError.ErrInvalidInput, "Invalid request body"),
			common.GenerateTraceID())
		return
	}

	// Set default limit
	if req.Limit <= 0 || req.Limit > 20 {
		req.Limit = 5
	}

	// Use empty profile if not provided
	if req.UserProfile == nil {
		req.UserProfile = make(map[string]interface{})
	}

	// Use empty items if not provided
	if req.AvailableItems == nil {
		req.AvailableItems = make([]map[string]interface{}, 0)
	}

	// Call AI service
	ctx := context.Background()
	recommendations, err := h.ai.GenerateRecommendations(ctx, req.UserProfile, req.AvailableItems)
	if err != nil {
		log.Printf("Recommendations error: %v", err)
		appError.WriteErrorResponse(w,
			appError.New(appError.ErrInternal, "Failed to generate recommendations"),
			common.GenerateTraceID())
		return
	}

	common.WriteSuccessResponse(w, recommendations, "Recommendations generated successfully")
}
